version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo:4.2
    ports:
      - 27017:27017
    restart: always
  recipes-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - 8080:8080
    links:
      - mongo
    restart: always
volumes:
  mongo-volume: